version: '3.8'

services:
  opensearch-test:
    image: opensearchproject/opensearch:2.15.0 # Using a specific version is good practice
    container_name: opensearch-test-node
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-test-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the ulimits below
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Small heap for testing
      # IMPORTANT: This disables the security plugin, making it easy to connect in tests
      - "DISABLE_SECURITY_PLUGIN=true"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    #   nofile:
    #     soft: 65536
    #     hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - opensearch-test-data:/usr/share/opensearch/data

volumes:
  opensearch-test-data:
